name: flutter_event_projections
description: Create queries for specific sets of data, that are updated asynchronously like streams.
version: 1.0.1
author: Horoliuk Maksym <goroliuk.maksym@gmail.com>
homepage: https://github.com/gorolykmaxim/flutter_event_projections

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  collection: ^1.14.11
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1